### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by thiphariel** [bbecquet/Leaflet.PolylineOffset#11]
Hi.

Have you planned to add your plugin published to npm ?
It's really useful when using Typescript to directly use npm package.

Thanks !

**Comment by bbecquet** [comment]
Done! And actually I have no good reason for why it wasn't done before :)

**Comment by thiphariel** [comment]
👍  Thanks !

**Comment by thiphariel** [comment]
A last question, I don't know if you already did that or not, but have you typings file for you plugin ?
Can it be easily generated ?

**Comment by bbecquet** [comment]
Hmm, I know almost nothing about typing files and TypeScript in general, and I've never tried it, so I won't be of much help. And I'm always reluctant to add code for a specific technology stack in my repos.
By reading about it I'm not sure it's easy to generate. And in this plugin case, it seems there would be a lot of things to write for the Leaflet types.
Incidentally, I've found this article which is about writing TypeScript def files for a Leaflet Plugin: http://peter.grman.at/how-to-write-typescript-definition-files/. Maybe you can find some useful stuff in it :)
But I don't know more, sorry.

**Comment by thiphariel** [comment]
I see. I will read the article and see what I can do.
I'm trying to build an app with your plugin using Angular 2 CLI, so it's full Typescript :D 

If I manage to get it fully works, I'll tell you :)

**Comment by bbecquet** [comment]
Thank you, it interests me greatly! Good luck for you project :)

**Comment by thiphariel** [comment]
Ok so... It's not really perfect but : It works ! x)

You can just import the module as it is, just be careful, remember to add it in ```system-config.js``` conf file in order to use it.
Then I import it directly like this ```import 'leaflet-polylineoffset';```to avoid angular2 CLI tree shacking :)

And it's worked nicely !

Thanks again for this plugin
