### ISSUE TITLE
Compatibility with Leaflet 1.x

### ISSUE THREAD

**Issue by BartWaardenburg** [bbecquet/Leaflet.PolylineOffset#12]
It seems that updating leaflet to any of the Leaflet 1.x versions will brake this plugin.

It would be really great if someone would be able to find where it breaks and how we can make this compatible again. I'll try to have a look as well.

**Comment by bbecquet** [comment]
I'll have a look tonight. I need to check all my plugins for compatibility with 1.0 anyway :) Thanks for reporting!

**Comment by bbecquet** [comment]
Hi. I've done some tests with Leaflet 1.0.1 and updated the three examples to use this version. Everything works fine for me, as it was before with the beta and the RC.

But maybe I've overlooked something. If you still experience problems, can you please describe where and how it fails? Console log at minimum, and if you can isolate the problem, please include the code causing it.

**Comment by BartWaardenburg** [comment]
I had the time to look further into it and it seems the hacky fix for #1 seemed to cause it. Looking for a workaround.
