### ISSUE TITLE
In extreme cases, points are far off

### ISSUE THREAD

**Issue by njbuch** [bbecquet/Leaflet.PolylineOffset#14]
Drawing a polyline with a 2px offset with many points (100+) in many angles I have several times seen serious issues with points that are on different continents.... Not sure if this is a duplicate.

**Comment by bbecquet** [comment]
Hi. Can you provide an example code with a minimal problematic polyline and your settings? I'll look into it when possible.
Thank you!

**Comment by njbuch** [comment]
Thanks for getting back, I am working on it already, will revert asap :)

**Comment by njbuch** [comment]
Here buddy, is my whale tracking problem. If you zoom in and out on the map you will see weird artifacts of drawing problems. Please notice that I place the current leaflet.polylineoffset.js file in the same folder, and just loaded the file with a browser.

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <title>Leaflet Polyline Offset - Cycle lanes example</title>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css" />
    <style>
      * { margin: 0; padding: 0; }
      html, body { height: 100%; }
      #map { width:100%; height:100%; }
    </style>

    <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
    <script src="leaflet.polylineoffset.js"></script>
    <script>
      window.onload = function () {
        var map = new L.Map('map', {
          center: [48.87, 2.355],
          zoom: 16,
          layers: [
            L.tileLayer('http://{s}.tile.openstreetmap.se/hydda/full/{z}/{x}/{y}.png', {
      			  minZoom: 0,
      			  maxZoom: 18,
      			  attribution: 'Tiles courtesy of <a href="http://openstreetmap.se/" target="_blank">OpenStreetMap Sweden</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
      			})
          ]
        });

        var coords =[[25.040588,-48.245438],[24.929695,-48.116005],[24.929695,-48.116005],[25.060501,-48.283718],[25.060501,-48.283718],[25.061325,-48.286362],[25.061325,-48.286362],[25.061325,-48.287186],[25.061325,-48.287186],[25.070114,-48.30014],[25.070114,-48.30014],[25.070801,-48.301056],[25.070801,-48.301056],[25.070703,-48.301546],[25.070703,-48.301546],[25.073719,-48.307064],[25.073719,-48.307064],[24.953659,-48.137222],[24.953659,-48.137222],[25.077667,-48.311527],[25.077667,-48.311527],[25.079899,-48.3129],[25.079899,-48.3129],[25.079899,-48.314445],[25.079899,-48.314445],[25.082016,-48.320969],[25.082016,-48.320969],[24.96711730957,-48.158920288086],[24.96711730957,-48.158920288086],[24.96711730957,-48.160293579102],[24.96711730957,-48.160293579102],[24.967941,-48.160019],[24.967941,-48.160019],[24.968147,-48.161667],[24.968147,-48.161667],[24.971237,-48.163727],[24.971237,-48.163727],[24.972610473633,-48.16716003418],[24.972610473633,-48.16716003418],[24.973068,-48.167618],[24.973068,-48.167618],[24.975357055664,-48.171279907227],[24.975357055664,-48.171279907227],[25.097581,-48.354613],[25.097581,-48.354613],[24.979476928711,-48.174026489258],[24.979476928711,-48.174026489258],[24.979476928711,-48.175399780273],[24.979476928711,-48.175399780273],[24.980850219727,-48.178146362305],[24.980850219727,-48.178146362305],[24.987442,-48.184738],[24.987442,-48.184738],[24.987717,-48.185013],[24.987717,-48.185013],[24.987716674805,-48.186386108398],[24.987716674805,-48.186386108398],[25.104446411133,-48.371780395508],[25.104446411133,-48.371780395508],[25.106644,-48.376312],[25.106644,-48.376312],[25.10856628418,-48.384140014648],[25.10856628418,-48.384140014648],[25.013809204102,-48.212478637695],[25.013809204102,-48.212478637695],[25.112686157227,-48.407485961914],[25.112686157227,-48.407485961914],[25.023422241211,-48.239944458008],[25.023422241211,-48.239944458008],[25.029831,-48.238113],[25.029831,-48.238113],[25.031661987305,-48.238571166992],[25.031661987305,-48.238571166992],[25.12532,-48.428085],[25.12532,-48.428085],[25.033035,-48.248184],[25.033035,-48.248184],[25.127243,-48.427261],[25.127243,-48.427261],[25.129165649414,-48.429458618164],[25.129165649414,-48.429458618164],[25.134658813477,-48.429458618164],[25.134658813477,-48.429458618164],[25.041566,-48.255675]];

    		var r = L.polyline(coords, {
          color: 'black', offset: 2,
          weight: 2, lineCap: 'round', lineJoin: 'round',
          opacity: 1
    		}).addTo(map);

    		map.fitBounds(r.getBounds());
      }
    </script>
  </head>

  <body>
    <div id="map"></div>
  </body>
</html>
`

**Comment by bbecquet** [comment]
Thanks a lot for providing the example!
Indeed things get really messy at low zoom levels. I would say it's probably related to the very acute angles, leading to loss of precision and aberrant value in some computations at low zoom level. I'll investigate, reducing your polyline to a problematic subpart to focus on it.

BTW, do you really use this plugin in a whale tracking application?? That's so great! I would love to hear more about that after I (hopefully) fix the bug :)

**Comment by bbecquet** [comment]
Hi! I've published a new version, with a lot of code cleaning and bug fixes.

It removes these crazy lines drawn all over the world when encountering special setups of very small angles and self-intersecting offset lines.
That said, the behaviour can still seem a bit strange at very zoomed-out views, but this is normal. IMO offsets cease to be useful at low zoom levels for small lines, I would advise just turning it off below a certain zoom level.

Can you please test the new version and tell me if it works better for you too? Thanks!

(BTW, your example polyline has an unrelated problem: all its points are duplicated. Just for a question of perfs, you should try removing them :))

**Comment by njbuch** [comment]
Thanks a lot, will try asap, but the software went out of the door, and there is probably a long horizon for next release. Makes sense with our comments on the zoom levels and line-sizes, thanks for those tips.
